#!/bin/bash
set -eu

### definitions
export PATH=$PWD/bin:$PATH
. CI/env
timestamp() { date +"%F %T.%N"; }
function runtest() {
    timestamp
    touch Makefile
    PYTEST_OPTIONS="
        --junit-xml=$CIRCLE_TEST_REPORTS/pytest/$CIRCLE_NODE_INDEX.$PYTHON.xml
        --junit-prefix=$PYTHON:
    " REQUIREMENTS=requirements.d/test.txt make test
}
function runlint() {
    timestamp
    touch Makefile
    REQUIREMENTS=requirements.d/lint.txt make lint
}
trap timestamp EXIT

### main
set -x
: $TOX_TESTENV_PASSENV

### machine
timestamp
lsb_release -a
test $CIRCLE_NODE_TOTAL -eq 4

### dependencies
timestamp
sudo apt-get install python2.7-dev python3.4-dev
pip install --upgrade -r CI/requirements.txt

### test
case "$CIRCLE_NODE_INDEX" in
0)
    export PYTHON=python2.7
    runlint
    ;;
1)
    export PYTHON=python3.4
    runlint
    ;;
2)
    export PYTHON=pypy
    ./CI/circle/install-pypy pypy-4.0.1-linux64
    ;;
3)
    export PYTHON=pypy3
    ./CI/circle/install-pypy pypy3-2.4.0-linux64
    ;;
esac
runtest
