#!/bin/bash
set -eu

### definitions
source CI/env
PATH=$PWD/CI/circle:$PATH
trap timestamp EXIT

### main
set -x
: $TOX_TESTENV_PASSENV

### machine
lsb_release -a
test $CIRCLE_NODE_TOTAL -eq 4

timestamp
sudo apt-get update
sudo apt-get install -y python2.7-dev

### per-node actions
timestamp
case $CIRCLE_NODE_INDEX in
0)  ## 13m
    ./CI/circle/install-python 2.7.10
    PYTHON=python2.7 runtest  # 6m

    ./CI/circle/install-python 2.6.8
    PYTHON=python2.6 runtest  # 7m
    ;;
1)  ## ???
    ./CI/circle/install-python 3.5.0
    PYTHON=python3.5 runtest  # 7.5m

    ./CI/circle/install-python 3.6.0
    PYTHON=python3.6 runtest  # ???
    ;;
2)  ## ???
    ./CI/circle/install-python 3.5.0
    PYTHON=python3.5 runlint  # 40s

    ./CI/circle/install-python 2.7.10
    PYTHON=python2.7 runlint  # 40s

    PYTHON=python3.5 runtest  # 7.5m
    ;;
3)  ## ???
    ./CI/circle/install-python pypy-4.0.1
    PYTHON=pypy runtest  # 9m
    ;;
esac
