#!/bin/bash
set -eux
timestamp
touch Makefile
PYTEST_OPTIONS="
    --junit-xml=$CIRCLE_TEST_REPORTS/pytest/$CIRCLE_NODE_INDEX.$PYTHON.xml
    --junit-prefix=$PYTHON:
" REQUIREMENTS=requirements.d/test.txt exec make test
