#!/bin/bash
set -eu
PYENV="$HOME/.pyenv"
CACHE="$HOME/.cache/pyenv"

# we always use the highest version on offer from pyenv
LATEST=$(
    pyenv install --list |
        egrep "^  $PY[.-][0-9.]+$" |
        tail -1
)

set -x
if ! [ -d $CACHE/$LATEST ]; then
    mkdir -p $CACHE/
    if [ -d $PYENV/versions/$LATEST ]; then
        ln -sf  $PYENV/versions/$LATEST $CACHE/$LATEST
    else
        $PYENV/plugins/python-build/bin/python-build $LATEST $CACHE/$LATEST
    fi
fi

ln -sfn $CACHE/$LATEST ~/python

# some of these come with ancient, broken virtualenvs installed
# we'll just use the system one
~/python/bin/pip uninstall --yes virtualenv || true
