#!/bin/bash
set -euo pipefail
export PY="$1"
export MAKE="$2"

export PATH=~/python:$PATH
# map "2.7" to "python2.7":
export PYTHON="$(sed 's/^[0-9]/python&/' <<< "$PY")"

set -x
./CI/install
./CI/make $MAKE
